# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e10e5c48554ff908fd1f3ca5b232621a035bfa93aeae2cbc47e3a98f4d02a774e3c18195af4a5d9f43a806befdc03a32f79442b101594fefa7e56399861e7a

test:
  secret_key_base: 7cc77e4e7f83197099fe6587c30c38dc7ade7afb824e19863bb301e1321e8f368b90ae02379a7620b3e9606a709159006ada54bc105509fe78d8d908dddab9ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
